### ISSUE TITLE
m71 webrtclib setup override documentation

### ISSUE THREAD

**Issue by ispysoftware** [webrtc-uwp/webrtc-uwp.github.io#4]
https://github.com/webrtc-uwp/webrtc-uwp.github.io/blob/James/20190225-m71-docs/how-to-device-capture-removal.md
- no override on m71 code takes 

Org.WebRtc.WebRtcLib.Setup(queue, false, true)

.. and it's not clear how the new config object can pass in the true/false flags.

**Comment by robin-raymond** [comment]
Correct, that is an error. There is a setup that takes a structure, and in there you can set true/false values related to what the docs talk about.

There exists a PR which addresses this issue.

**Comment by ispysoftware** [comment]
in m71 the setup takes a configuration from:

`internal interface IWebRtcLibConfiguration

    {

        IEventQueue AudioCaptureFrameProcessingQueue { get; set; }

        IEventQueue AudioRenderFrameProcessingQueue { get; set; }

        IEventQueue Queue { get; set; }

        IEventQueue VideoFrameProcessingQueue { get; set; }

    }`

- I can't see where to set true/false values in there?

**Comment by jamescadd** [comment]
We were both looking in the wrong place - this is in PeerCC Factory.  Here's the struct, will update docs:

`
/// <summary>
   /// The WebRtcFactoryConfiguration contains the boot strapping
   /// configuration options for the WebRtcFactory.
   /// </summary>
   [dictionary]
   struct WebRtcFactoryConfiguration
   {

     /// <summary>
     /// Gets or sets if audio capturing is enabled.
     /// </summary>
     bool audioCapturingEnabled = true;

     /// <summary>
     /// Gets or sets if audio rendering is enabled.
     /// </summary>
     bool audioRenderingEnabled = true;

     /// <summary>
     /// Gets or sets if audio post-capture and pre-render events should be
     /// enabled.
     /// </summary>
     bool enableAudioBufferEvents = false;
   };
`

**Comment by jamescadd** [comment]
Docs updated.
